export component MainWindow inherits Window {
    background: transparent;
    title: "VoidPath ED";
    always-on-top: true;
    no-frame: true;
    height: 160px;
    width: 600px;

    in property <bool> is-route: false;
    in property <bool> is-searching-route: false;

    callback close-window();
    callback search-route();
    callback open-settings();

    Rectangle {
        background: #2A2A2A;
        border-radius: 6px;
        height: 100%;
        width: 100%;

        VerticalLayout {
            HorizontalLayout {
                alignment: space-between;
                padding-bottom: 0px;
                padding-right: 10px;
                padding-left: 10px;
                padding-top: 10px;
                height: 36px;

                Rectangle {
                    height: 16px;
                    width: 16px;

                    Image {
                        colorize: settings-area.has-hover ? #ffffff : #707070;
                        source: @image-url("assets/settings.svg");
                        height: 16px;
                        width: 16px;
                    }

                    settings-area := TouchArea {
                        clicked => { root.open-settings(); }
                    }
                }

                Rectangle {
                    height: 16px;
                    width: 16px;

                    Image {
                        colorize: close-area.has-hover ? #ff5f57 : #707070;
                        source: @image-url("assets/close.svg");
                        height: 16px;
                        width: 16px;
                    }

                    close-area := TouchArea {
                        clicked => { root.close-window(); }
                    }
                }
            }

            if !is-route: VerticalLayout {
                padding-bottom: 40px;
                vertical-stretch: 1;
                alignment: center;
                padding-top: 0px;
                spacing: 8px;

                HorizontalLayout {
                    alignment: center;

                    Image {
                        source: @image-url("assets/no_route.svg");
                        colorize: #5DCAA5;
                        height: 32px;
                        width: 32px;
                    }
                }

                Text {
                    text: "There is no active route";
                    horizontal-alignment: center;
                    font-family: "Inter";
                    font-italic: true;
                    font-weight: 100;
                    color: #FFFFFF;
                    font-size: 12px;
                }

                HorizontalLayout {
                    alignment: center;
                    padding-top: 5px;

                    Rectangle {
                        background: search-btn.has-hover ? #4db896 : #5DCAA5;
                        border-radius: 8px;
                        height: 24px;
                        width: 60px;

                        Image {
                            source: @image-url("assets/search.svg");
                            colorize: #000000;
                            height: 24px;
                            width: 24px;
                        }

                        search-btn := TouchArea {
                            clicked => { root.search-route() }
                        }
                    }
                }
            }
        }
    }
}
